//-- Generated by LFC @ 2021/07/26 14:57:03 --//
#![allow(unused_imports)]
#![allow(non_snake_case)]

#[macro_use]
extern crate reactor_rt;

mod reactors;

use ::reactor_rt::*;
use self::reactors::MinimalDispatcher as _MainReactor;
use self::reactors::MinimalParams as _MainParams;

fn main() {

    // todo CLI parsing
    let options = SchedulerOptions {
       timeout: None,
       keep_alive: false
    };
    let main_args = _MainParams {
       // todo, for now main reactor params are unsupported
    };

    SyncScheduler::run_main::<_MainReactor>(options, main_args);
}
